version: "3.7"

services:
  legacy-web:
    image: nurih/demo-monolith:latest
    build: ./monolith-app
    ports:
      - 3000:3000
    depends_on:
      - legacy-db
    environment:
      MONGO_URL1: 'mongodb://legacy-db:27017/appDemo1'
    # networks:
    #   - back
    #   - front
  legacy-db:
    image: mongo:4.0
    ports: 
      - 27017:27017
    # networks:
    #   - back
# networks: 
#   back:
#   front:
